# Site settings
title: Diamond Ridge Construction
email: diamondridgeconstruction963@yahoomail.com
# url: https://example.github.io
description: "Building on a foundation of trust, where quality meets craftsmanship"

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary-dark: '#05360c'
  primary-dark: '#35523d'
  links: '#219ab3'

# Footer settings
footer: Diamond Ridge Construction

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: instagram
    # url: https://www.instagram.com/withfarmerscanada/
  # - title: facebook
    # url:
  # - title: stack-overflow
    # url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
    # url: http://bitbucket.org/jekyll
  # - title: github
    # url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
